In [2]:
import pandas as pd 
import numpy as np

In [3]:
file_path = "/Users/athuldas/Documents/DS/Internship/Projects/New project/Detailed India EV Market Data 2001 - 2024/csv's/"

In [4]:
file_name1 = "Fact_Category.csv"

In [5]:
file_name2 = "Fact_MakerSales.csv"

In [6]:
file_name3 = "CategoryMap.csv"

In [7]:
file_name4 = "Dim_MakerLocation.csv"

In [8]:
file_name5 = "Dim_State.csv"

In [9]:
file_name6 = "Maker_State_Presence.csv"

In [10]:
fact_category = pd.read_csv(file_path+file_name1)

In [11]:
fact_category.head()

,Date,Year,RawCategory,Registrations,CategoryGroup
0,2001-01-01,2001,FOUR WHEELER (INVALID CARRIAGE),0,4W
1,2001-01-01,2001,HEAVY GOODS VEHICLE,1,Commercial
2,2001-01-01,2001,HEAVY MOTOR VEHICLE,0,Commercial
3,2001-01-01,2001,HEAVY PASSENGER VEHICLE,0,Commercial
4,2001-01-01,2001,LIGHT GOODS VEHICLE,9,4W

In [12]:
fact_makersales = pd.read_csv(file_path+file_name2)

In [14]:
fact_makersales.head()

,MakerSalesID,Maker,RawCategory,Year,Sales,CategoryGroup
0,1,"""VOLVO GROUP INDIA PVT LTD""",3W,2015,0,3W
1,2,"""VOLVO GROUP INDIA PVT LTD""",3W,2016,0,3W
2,3,"""VOLVO GROUP INDIA PVT LTD""",3W,2017,31,3W
3,4,"""VOLVO GROUP INDIA PVT LTD""",3W,2018,12,3W
4,5,"""VOLVO GROUP INDIA PVT LTD""",3W,2019,0,3W

In [13]:
categorymap = pd.read_csv(file_path+file_name3)

In [15]:
categorymap.head()

                       RawCategory CategoryGroup
0                               2W            2W
1                               3W            3W
2  FOUR WHEELER (INVALID CARRIAGE)            4W
3              HEAVY GOODS VEHICLE    Commercial
4              HEAVY MOTOR VEHICLE    Commercial

In [16]:
dim_makerlocation = pd.read_csv(file_path+file_name4)

In [17]:
dim_makerlocation.head()

                       Maker       Place       State
0       Ajanta Manufacturing       Morbi     Gujarat
1  Altigreen Propulsion Labs   Bengaluru   Karnataka
2            Ampere Vehicles  Coimbatore  Tamil Nadu
3              Ashok Leyland     Chennai  Tamil Nadu
4     Ashok Leyland (EV Bus)       Alwar   Rajasthan

In [18]:
dim_state = pd.read_csv(file_path+file_name5)

In [22]:
dim_state

,StateID,State,MakerCount,MakersList,NoOfOperationalPCs
0,1,Andhra Pradesh,1,Kia Motors India,327
1,2,Delhi,4,"Dilli Electric Auto Pvt Ltd, Euler Motors, Her...",1886
2,3,Gujarat,5,"Ajanta Manufacturing, Atul Auto, Electrotherm ...",476
3,4,Haryana,6,"Hero MotoCorp, JBM Auto, Maruti Suzuki India, ...",377
4,5,Karnataka,6,"Altigreen Propulsion Labs, Ather Energy, Bosch...",1041
5,6,Madhya Pradesh,1,Volvo Eicher,341
6,7,Maharashtra,15,"Audi India, Bajaj Auto, Bajaj Auto (EV), Bhara...",3079
7,8,Punjab,1,SML Isuzu,158
8,9,Rajasthan,4,"Ashok Leyland (EV Bus), HOP Electric Mobility,...",500
9,10,Tamil Nadu,11,"Ampere Vehicles, Ashok Leyland, BYD India, Cit...",643
10,11,Telangana,3,"Etrio Automobiles, Gayam Motor Works, Olectra ...",481
11,12,Uttarakhand,1,Lohia Auto Industries,76
12,13,West Bengal,3,"Exide Industries, Hindustan Motors, Jezza Motors",318

In [20]:
maker_statepresence = pd.read_csv(file_path+file_name6)

In [21]:
maker_statepresence.head()

                       Maker       State
0       Ajanta Manufacturing     Gujarat
1  Altigreen Propulsion Labs   Karnataka
2            Ampere Vehicles  Tamil Nadu
3              Ashok Leyland  Tamil Nadu
4     Ashok Leyland (EV Bus)   Rajasthan

In [23]:
#####################################################
                  #data checks
#####################################################

In [24]:
################# Fact category

In [26]:
fact_category.shape

(4528, 5)

In [30]:
fact_category.columns

Index(['Date', 'Year', 'RawCategory', 'Registrations', 'CategoryGroup'], dtype='object')

In [31]:
fact_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4528 entries, 0 to 4527
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           4528 non-null   object
 1   Year           4528 non-null   int64
 2   RawCategory    4528 non-null   object
 3   Registrations  4528 non-null   int64
 4   CategoryGroup  4528 non-null   object
dtypes: int64(2), object(3)
memory usage: 177.0+ KB

In [32]:
fact_category.duplicated().sum()

np.int64(0)

In [37]:
fact_category["RawCategory"].unique()

array(['FOUR WHEELER (INVALID CARRIAGE)', 'HEAVY GOODS VEHICLE',
       'HEAVY MOTOR VEHICLE', 'HEAVY PASSENGER VEHICLE',
       'LIGHT GOODS VEHICLE', 'LIGHT MOTOR VEHICLE',
       'LIGHT PASSENGER VEHICLE', 'MEDIUM GOODS VEHICLE',
       'MEDIUM PASSENGER VEHICLE', 'MEDIUM MOTOR VEHICLE',
       'OTHER THAN MENTIONED ABOVE', 'THREE WHEELER(NT)',
       'TWO WHEELER (INVALID CARRIAGE)', 'THREE WHEELER(T)',
       'TWO WHEELER(NT)', 'TWO WHEELER(T)'], dtype=object)

In [38]:
fact_category["CategoryGroup"].unique()

array(['4W', 'Commercial', 'Other', '3W', '2W'], dtype=object)

In [41]:
# no of records : 4528
# columns       : 'Date', 'Year', 'RawCategory', 'Registrations', 'CategoryGroup'
# no duplicate records
# no missing values 
# !! date format issue date column is saved as datatype object (up for cleaning)
# 16 raw categories .
# 5 category groups

In [42]:
################# Fact makersales

In [43]:
fact_makersales.shape

(13860, 6)

In [44]:
fact_makersales.columns

Index(['MakerSalesID', 'Maker', 'RawCategory', 'Year', 'Sales',
       'CategoryGroup'],
      dtype='object')

In [45]:
fact_makersales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13860 entries, 0 to 13859
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MakerSalesID   13860 non-null  int64
 1   Maker          13860 non-null  object
 2   RawCategory    13860 non-null  object
 3   Year           13860 non-null  int64
 4   Sales          13860 non-null  int64
 5   CategoryGroup  13860 non-null  object
dtypes: int64(3), object(3)
memory usage: 649.8+ KB

In [46]:
fact_makersales.duplicated().sum()

np.int64(0)

In [47]:
fact_makersales["Year"].min()

2015

In [48]:
fact_makersales["Year"].max()

2024

In [49]:
# no of records   : 13860
# columns         : 'MakerSalesID', 'Maker', 'RawCategory', 'Year', 'Sales', 'CategoryGroup'
# no duplicate records
# no missing value
# no datatype issue
# data ranges from 2015 to 2024

In [50]:
################# Categorymap

In [51]:
categorymap.shape

(20, 2)

In [52]:
categorymap.columns

Index(['RawCategory', 'CategoryGroup'], dtype='object')

In [53]:
categorymap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   RawCategory    20 non-null     object
 1   CategoryGroup  20 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes

In [55]:
categorymap.duplicated().sum()

np.int64(0)

In [57]:
categorymap["CategoryGroup"].unique()

array(['2W', '3W', '4W', 'Commercial', 'Other'], dtype=object)

In [58]:
# no of records     : 20
# columns           : 'RawCategory', 'CategoryGroup'
# no duplicate records
# no missing values
# there are 20 RawCategories and 5 category groups

In [59]:
################# Dim makerlocation

In [60]:
dim_makerlocation.shape

(61, 3)

In [61]:
dim_makerlocation.columns

Index(['Maker', 'Place', 'State'], dtype='object')

In [62]:
dim_makerlocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Maker   61 non-null     object
 1   Place   61 non-null     object
 2   State   61 non-null     object
dtypes: object(3)
memory usage: 1.6+ KB

In [68]:
dim_makerlocation.duplicated(subset = "Maker").sum()

np.int64(0)

In [66]:
dim_makerlocation["State"].unique()

array(['Gujarat', 'Karnataka', 'Tamil Nadu', 'Rajasthan', 'Maharashtra',
       'Delhi', 'Telangana', 'West Bengal', 'Haryana', 'Andhra Pradesh',
       'Uttarakhand', 'Punjab', 'Madhya Pradesh'], dtype=object)

In [69]:
# no of records     : 61
# columns           : 'Maker', 'Place', 'State'
# no missing values
# no duplicate records
# there are 13 states and 61 makers

In [71]:
################# Dim state

In [72]:
dim_state.shape

(13, 5)

In [73]:
dim_state.columns

Index(['StateID', 'State', 'MakerCount', 'MakersList', 'NoOfOperationalPCs'], dtype='object')

In [74]:
dim_state.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   StateID             13 non-null     int64
 1   State               13 non-null     object
 2   MakerCount          13 non-null     int64
 3   MakersList          13 non-null     object
 4   NoOfOperationalPCs  13 non-null     int64
dtypes: int64(3), object(2)
memory usage: 652.0+ bytes

In [75]:
dim_state.duplicated().sum()

np.int64(0)

In [76]:
# no of records. : 13
# columns        : 'StateID', 'State', 'MakerCount', 'MakersList', 'NoOfOperationalPCs'
# no duplicated records
# no missing values
# there are 13 states

In [77]:
################# maker statepresence

In [78]:
maker_statepresence.shape

(61, 2)

In [79]:
maker_statepresence.columns

Index(['Maker', 'State'], dtype='object')

In [80]:
maker_statepresence.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Maker   61 non-null     object
 1   State   61 non-null     object
dtypes: object(2)
memory usage: 1.1+ KB

In [81]:
maker_statepresence.duplicated().sum()

np.int64(0)

In [82]:
# no of records   : 61
# columns         :'Maker', 'State'
# no missing values
# no duplicate records

In [84]:
#####################################################
                  # Detailed EDA
#####################################################

In [86]:
# Total sales all years

In [101]:
total_sales_all_years = fact_makersales["Sales"].sum()

In [102]:
total_sales_all_years

np.int64(4420903)

In [87]:
# top 10 makers by cumulative sales

In [99]:
top_10_makers_by_sales = fact_makersales.groupby(by=["Maker"]).agg({"Sales":"sum"}).sort_values(by="Sales",ascending=False).head(10)

In [100]:
top_10_makers_by_sales

                                    Sales
Maker
OLA ELECTRIC TECHNOLOGIES PVT LTD  588266
TVS MOTOR COMPANY LTD              318445
ATHER ENERGY PVT LTD               236387
HERO ELECTRIC VEHICLES PVT. LTD    201785
BAJAJ AUTO LTD                     198498
OKINAWA AUTOTECH PVT LTD           196182
YC ELECTRIC VEHICLE                152951
AMPERE VEHICLES PRIVATE LIMITED    141805
SAERA ELECTRIC AUTO PVT LTD         87481
MAHINDRA & MAHINDRA LIMITED         84794

In [ ]:
#